"""
noah_source_scatter.py
======================
Publication-quality figure defending the use of NOAH 5-yr flood hazard maps as
spatial ground truth.

For each of the 10 study cities, we ask: does observed flood intensity increase
monotonically with NOAH hazard class (None → Low → Medium → High)?

We answer this across three fully independent data sources:

  AI4G   — Sentinel-1 SAR flood detections, 10 years (Oct 2014–Sep 2024),
            20 m resolution.  Metric: fraction of observation dates with a
            detection (flood frequency).
  PhilSA — Multi-sensor SAR flood extents, 2022–2026, from HDX.
            Metric: fraction of PhilSA events with a detection (event frequency).
  Aq.    — WRI Aqueduct Floods v2 (WATCH historical, RP-5 riverine),
            model-based, ~1 km.  Metric: inundation depth (metres).

Visual design
-------------
  • 10 subplots arranged 2 rows × 5 columns (one per city).
  • X-axis: NOAH hazard class (0 = None, 1 = Low, 2 = Medium, 3 = High).
  • Y-axis: normalised flood metric (each source independently max-scaled
    to [0, 1] within the city so all three lines share the same axis).
  • For each source × NOAH class:
      – Thin scatter of individual 250 m cells (jittered, low alpha).
      – Filled box (IQR) + median line (solid) showing the central tendency.
      – Line connecting class medians to make the gradient readable.
  • Spearman ρ annotated per source.
  • Shaded background bands to guide the eye between hazard classes.

Inputs (generated by the comparison scripts)
--------------------------------------------
  output/noah_validation/ai4g/noah_ai4g_cells.parquet
  output/noah_validation/philsa/noah_philsa_allfiles_cells.parquet
  output/noah_validation/aqueduct/noah_aqueduct_cells.parquet

Output
------
  output/noah_validation/noah_source_scatter.png
"""

import os
import warnings

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VAL_DIR = os.path.join(ROOT, "output", "noah_validation")
OUT_DIR = VAL_DIR

AI4G_CELLS   = os.path.join(VAL_DIR, "ai4g",    "noah_ai4g_cells.parquet")
PHILSA_CELLS = os.path.join(VAL_DIR, "philsa",  "noah_philsa_allfiles_cells.parquet")
AQ_CELLS     = os.path.join(VAL_DIR, "aqueduct","noah_aqueduct_cells.parquet")

# Canonical city order
CITY_ORDER = [
    "Tuguegarao", "Ilagan", "Dagupan", "San Fernando", "Manila",
    "Naga", "Daet", "Cagayan de Oro", "Butuan", "Cotabato",
]

REGION_LABELS = {
    "Manila":         "NCR",
    "San Fernando":   "C. Luzon",
    "Dagupan":        "Ilocos",
    "Naga":           "Bicol",
    "Daet":           "Bicol",
    "Cagayan de Oro": "N. Mindanao",
    "Butuan":         "Caraga",
    "Tuguegarao":     "Cagayan\nValley",
    "Ilagan":         "Cagayan\nValley",
    "Cotabato":       "BARMM",
}

SOURCES = [
    {
        "label":  "AI4G (SAR, 10 yr)",
        "col":    "ai4g_freq",
        "color":  "#1565C0",
        "marker": "o",
        "zorder": 4,
    },
    {
        "label":  "PhilSA (SAR, 2022–26)",
        "col":    "philsa_freq",
        "color":  "#6A1B9A",
        "marker": "s",
        "zorder": 3,
    },
    {
        "label":  "Aqueduct (model, RP-5)",
        "col":    "aq_depth",
        "color":  "#2E7D32",
        "marker": "^",
        "zorder": 2,
    },
]

CLASS_LABELS = ["None\n(0)", "Low\n(1)", "Med.\n(2)", "High\n(3)"]
CLASS_SHADE  = ["#FFFFFF", "#FFFDE7", "#FFF3E0", "#FFEBEE"]   # subtle tints

# ---------------------------------------------------------------------------
# Load per-cell data and merge on city + grid coordinates
# ---------------------------------------------------------------------------
print("Loading per-cell data…", flush=True)

def _load(path, metric_col, rename):
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found — run the corresponding comparison script first."
        )
    df = pd.read_parquet(path)
    # Aqueduct has nodata NaN in aq_depth; replace with 0
    if metric_col in df.columns:
        df[metric_col] = df[metric_col].fillna(0).clip(lower=0)
    df = df.rename(columns={metric_col: rename})
    keep = ["city", "lon", "lat", "noah_cls", "is_water", rename]
    return df[[c for c in keep if c in df.columns]]

ai4g_df   = _load(AI4G_CELLS,   "ai4g_freq",   "ai4g_freq")
philsa_df = _load(PHILSA_CELLS, "philsa_freq", "philsa_freq")
aq_df     = _load(AQ_CELLS,     "aq_depth",    "aq_depth")

# Round lon/lat to 5 dp for merge key
for df in [ai4g_df, philsa_df, aq_df]:
    df["lon_r"] = df["lon"].round(5)
    df["lat_r"] = df["lat"].round(5)

# Merge: start from Aqueduct (has all 10 cities), left-join the observational sources
merged = (
    aq_df
    .merge(ai4g_df  [["city","lon_r","lat_r","ai4g_freq",   "is_water"]],
           on=["city","lon_r","lat_r"], how="left", suffixes=("","_ai4g"))
    .merge(philsa_df[["city","lon_r","lat_r","philsa_freq"]],
           on=["city","lon_r","lat_r"], how="left")
)
# is_water: use whichever is available
if "is_water_ai4g" in merged.columns:
    merged["is_water"] = merged["is_water"].fillna(merged["is_water_ai4g"])
merged = merged.drop(columns=[c for c in merged.columns if c.endswith("_ai4g")], errors="ignore")
merged["ai4g_freq"]   = merged["ai4g_freq"].fillna(0)
merged["philsa_freq"] = merged["philsa_freq"].fillna(0)

print(f"  Merged: {len(merged):,} cells across "
      f"{merged['city'].nunique()} cities", flush=True)

# ---------------------------------------------------------------------------
# Normalise each source per city (0–1 within city)
# ---------------------------------------------------------------------------
def _norm(series):
    mx = series.max()
    return series / mx if mx > 0 else series * 0

for city_name, grp_idx in merged.groupby("city").groups.items():
    for src in SOURCES:
        col = src["col"]
        if col in merged.columns:
            mx = merged.loc[grp_idx, col].max()
            merged.loc[grp_idx, col + "_norm"] = (
                merged.loc[grp_idx, col] / mx if mx > 0 else 0.0
            )

# Add normalised col names to SOURCES lookup
for src in SOURCES:
    src["norm_col"] = src["col"] + "_norm"

# ---------------------------------------------------------------------------
# Compute per-city stats: median + IQR per NOAH class per source
# ---------------------------------------------------------------------------
def _box_stats(vals):
    """Return (median, q25, q75) for a 1-D array."""
    if len(vals) == 0:
        return np.nan, np.nan, np.nan
    return np.nanmedian(vals), np.nanpercentile(vals, 25), np.nanpercentile(vals, 75)

def _spearman(x, y):
    s = pd.Series(x).corr(pd.Series(y), method="spearman")
    return float(s) if pd.notna(s) else np.nan

print("Computing city statistics…", flush=True)
city_stats = {}
for city_name in CITY_ORDER:
    sub = merged[(merged["city"] == city_name) & (~merged["is_water"])].copy()
    if sub.empty:
        continue
    per_class = {}
    for cls in [0, 1, 2, 3]:
        cls_sub = sub[sub["noah_cls"] == cls]
        per_class[cls] = {}
        for src in SOURCES:
            nc = src["norm_col"]
            if nc not in cls_sub.columns:
                per_class[cls][src["label"]] = (np.nan, np.nan, np.nan)
                continue
            per_class[cls][src["label"]] = _box_stats(cls_sub[nc].values)
    # Spearman ρ (raw metric vs noah_cls)
    rhos = {}
    for src in SOURCES:
        col = src["col"]
        if col not in sub.columns:
            rhos[src["label"]] = np.nan
            continue
        n_cls = sub["noah_cls"].values
        vals  = sub[col].values
        if len(np.unique(n_cls)) > 1 and len(np.unique(vals)) > 1:
            rhos[src["label"]] = _spearman(n_cls, vals)
        else:
            rhos[src["label"]] = np.nan
    city_stats[city_name] = {"per_class": per_class, "rhos": rhos, "n": len(sub)}
    print(f"  {city_name}: n={len(sub):,}  " +
          "  ".join(f"ρ_{src['label'].split()[0]}={rhos[src['label']]:.2f}"
                    if pd.notna(rhos[src['label']]) else f"ρ_{src['label'].split()[0]}=—"
                    for src in SOURCES), flush=True)

# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------
print("\nRendering figure…", flush=True)

NCOLS = 5
NROWS = 2
fig, axes = plt.subplots(
    NROWS, NCOLS,
    figsize=(18, 7.5),
    sharey=False,
)
fig.patch.set_facecolor("#F8F8F8")

fig.suptitle(
    "NOAH 5-yr Hazard Class vs Independently-Observed Flood Intensity\n"
    "Three sources, 10 cities — each source normalised to [0, 1] within city",
    fontsize=13, fontweight="bold", y=1.01,
)

JITTER_W = 0.12   # horizontal jitter width per source
BOX_W    = 0.18   # half-width of IQR box

src_offsets = [-0.28, 0.0, 0.28]   # x-offsets for three sources

for idx, city_name in enumerate(CITY_ORDER):
    row, col = divmod(idx, NCOLS)
    ax = axes[row, col]
    ax.set_facecolor("#FAFAFA")

    if city_name not in city_stats:
        ax.text(0.5, 0.5, f"{city_name}\n(no data)",
                ha="center", va="center", transform=ax.transAxes, fontsize=9)
        ax.axis("off")
        continue

    stats = city_stats[city_name]

    # Shade background per NOAH class
    for cls in [0, 1, 2, 3]:
        ax.axvspan(cls - 0.5, cls + 0.5, color=CLASS_SHADE[cls], zorder=0)

    city_sub = merged[(merged["city"] == city_name) & (~merged["is_water"])]

    for si, src in enumerate(SOURCES):
        nc     = src["norm_col"]
        color  = src["color"]
        offset = src_offsets[si]

        if nc not in city_sub.columns:
            continue

        # ── Scatter (jittered) ────────────────────────────────────────────
        xs, ys = [], []
        for cls in [0, 1, 2, 3]:
            vals = city_sub.loc[city_sub["noah_cls"] == cls, nc].values
            if len(vals) == 0:
                continue
            # Downsample to max 600 pts per class for speed/readability
            if len(vals) > 600:
                vals = np.random.choice(vals, 600, replace=False)
            jx = cls + offset + np.random.uniform(
                -JITTER_W / 2, JITTER_W / 2, len(vals)
            )
            xs.extend(jx)
            ys.extend(vals)
        if xs:
            ax.scatter(xs, ys, s=2.5, color=color, alpha=0.12,
                       linewidths=0, zorder=src["zorder"])

        # ── Box (IQR) + median line ───────────────────────────────────────
        medians = []
        for cls in [0, 1, 2, 3]:
            med, q25, q75 = stats["per_class"][cls].get(src["label"], (np.nan, np.nan, np.nan))
            x = cls + offset
            if not np.isnan(med):
                # IQR box
                ax.add_patch(plt.Rectangle(
                    (x - BOX_W, q25), 2 * BOX_W, q75 - q25,
                    facecolor=color, alpha=0.28, edgecolor=color,
                    linewidth=0.8, zorder=src["zorder"] + 1,
                ))
                # Median line
                ax.plot([x - BOX_W, x + BOX_W], [med, med],
                        color=color, linewidth=2.0, zorder=src["zorder"] + 2)
            medians.append((cls + offset, med))

        # ── Connect medians with a line ───────────────────────────────────
        valid_meds = [(x, y) for x, y in medians if not np.isnan(y)]
        if len(valid_meds) >= 2:
            mx, my = zip(*valid_meds)
            ax.plot(mx, my, color=color, linewidth=1.4, linestyle="--",
                    alpha=0.70, zorder=src["zorder"] + 3)

    # ── Spearman ρ annotations ────────────────────────────────────────────
    rho_lines = []
    for src in SOURCES:
        rho = stats["rhos"].get(src["label"], np.nan)
        tag = src["label"].split("(")[0].strip()
        rho_lines.append(
            f"ρ {tag}: {'—' if np.isnan(rho) else f'{rho:+.2f}'}"
        )
    ax.text(
        0.97, 0.97, "\n".join(rho_lines),
        transform=ax.transAxes, va="top", ha="right",
        fontsize=6.2, family="monospace",
        bbox=dict(facecolor="white", alpha=0.85, boxstyle="round,pad=0.25",
                  edgecolor="#cccccc"),
        zorder=10,
    )

    # ── Axes formatting ───────────────────────────────────────────────────
    ax.set_xlim(-0.6, 3.6)
    ax.set_ylim(-0.04, 1.12)
    ax.set_xticks([0, 1, 2, 3])
    ax.set_xticklabels(CLASS_LABELS, fontsize=7.5)
    ax.yaxis.set_major_locator(mticker.MultipleLocator(0.25))
    ax.tick_params(axis="y", labelsize=7)
    ax.grid(axis="y", alpha=0.35, linewidth=0.6)
    ax.axhline(0, color="#aaa", linewidth=0.5)

    title_city   = city_name
    title_region = REGION_LABELS.get(city_name, "")
    ax.set_title(f"{title_city}\n{title_region}",
                 fontsize=9, fontweight="bold", pad=4)

    if col == 0:
        ax.set_ylabel("Normalised flood metric", fontsize=8)
    if row == NROWS - 1:
        ax.set_xlabel("NOAH hazard class", fontsize=8)

# ── Legend ────────────────────────────────────────────────────────────────
legend_handles = [
    mpatches.Patch(facecolor=src["color"], alpha=0.75, label=src["label"])
    for src in SOURCES
]
legend_handles += [
    mpatches.Patch(facecolor=c, edgecolor="#aaa", linewidth=0.5, label=lbl)
    for c, lbl in zip(CLASS_SHADE[1:], ["NOAH Low", "NOAH Medium", "NOAH High"])
]
fig.legend(
    handles=legend_handles,
    loc="lower center",
    ncol=6,
    fontsize=8.5,
    framealpha=0.95,
    bbox_to_anchor=(0.5, -0.04),
)

fig.text(
    0.5, -0.07,
    "Each point = one 250 m grid cell (permanent water excluded).  "
    "Box = IQR, horizontal line = median.  "
    "Metrics normalised to city maximum within each source.  "
    "Positive Spearman ρ means observed flooding increases with NOAH hazard class.",
    ha="center", fontsize=7.5, color="#555555",
)

fig.tight_layout(rect=[0, 0.01, 1, 0.995])

out_path = os.path.join(OUT_DIR, "noah_source_scatter.png")
fig.savefig(out_path, dpi=160, bbox_inches="tight")
plt.close(fig)

print(f"\n  Saved → {out_path}", flush=True)
print("DONE", flush=True)
